# TODO: Remove everything that is redundant
# TODO: Add comments to all settings

preferences:
  general:
    audioLib: sounddevice
    units: deg

window:
  size: [2560, 1600]
  pos: [0, 0]
  color: [1, 1, 1] 
  fullscr: True 
  winType: pyglet
  waitBlanking: True

monitor:
  name: my-screen
  width: 30.41  # in cm 
  distance: 70  # in cm 
  gamma: 1

mouse:
  visible: False

eyetracker:
  # address: '100.1.1.1'
  address: None # use this for dummy mode (LK)
  dot_size: 0.1  # in deg
  options:
    active_eye: left  # [right]
    binocular_enabled: NO  # [YES]
    heuristic_filter: 2  # [0, OFF, 1, ON]
    pupil_size_diameter: YES  # [NO]
    #simulate_head_camera: NO  # [YES]  # GIVES ERROR?
    #simulation_screen_distance
    file_event_filter: 'LEFT,RIGHT,FIXATION,SACCADE,BLINK,MESSAGE,BUTTON,INPUT'
    link_event_filter: 'LEFT,RIGHT,FIXATION,SACCADE,BLINK,BUTTON'
    link_sample_data: 'LEFT,RIGHT,GAZE,GAZERES,AREA,STATUS,HTARGET'
    #file_sample_data: LEFT,RIGHT,GAZE,AREA,GAZERES,STATUS,HTARGET,INPUT'  # GIVES ERROR?
    calibration_type: HV5  # [H3, HV3, HV5, HV9]
    x_gaze_constraint: AUTO
    y_gaze_constraint: AUTO
    enable_automatic_calibration: YES  # [NO]
    automatic_calibration_pacing: 1000
    enable_search_limits: YES
    track_search_limits: YES
    autothreshold_click: YES
    autothreshold_repeat: YES
    enable_camera_position_detect: YES
    sample_rate: 1000

mri:
  simulate: True # set to FALSE when using actual mri
  TR: 2.0  # seconds between volume acquisitions
  TA: 2.0  # seconds to acquire one slice (?)
  volumes: 10  # number of 3D volumes to obtain in a given scanning run
  sync: t  # character used as flag for sync timing, default=‘5’
  skip: 0  # how many frames to silently omit initially during T1 stabilization, no sync pulse.
  sound: False  # simulate scanner noise

language_localizer:
  responses:
    attention_check: space
    escape: escape
  stimuli: 
    phase_name_blank: ll_blank
    phase_name_word: ll_word
    phase_name_attention: ll_attention
    phase_name_fix: ll_fix
    phase_duration_blank: 100
    phase_duration_word: 450
    phase_duration_attention: 400
    phase_duration_fix: 1400
    text_color: [-1, -1, -1]
    fix_color: [-1, -1, -1]
    win_color: [1, 1, 1]
  mri:
    sync: t
  text:
    instructions: This is the instruction text
    awaiting_scanner: Waiting for scanner ...
